# Generated by Django 3.0.2 on 2020-01-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('MD5', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('ReleaseDate', models.CharField(max_length=100)),
                ('Version', models.CharField(max_length=100)),
                ('URL', models.TextField(max_length=100)),
            ],
        ),
    ]
